services:
  tests:
    image: ghcr.io/afiffon/smb-tests:latest
    build:
      context: crates/smb/tests
      dockerfile: Dockerfile
      tags:
        - ghcr.io/afiffon/smb-tests:latest
      platforms:
        - linux/amd64
    ports:
      - 88:88/tcp
      - 88:88/udp
      - 445:445
      - 139:139
    hostname: samba
    networks:
      default:
        aliases:
          - samba.smb.test
      default2: {}
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    healthcheck:
      test: ["CMD-SHELL", "smbclient //samba.smb.test/KerberosShare --use-kerberos=required -U 'LocalAdmin%123456' -c ls >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      SMB_RUST_TESTS_SERVER: samba
      SMB_RUST_TESTS_KERBEROS_SERVER: samba.smb.test
      SSPI_KDC_URL: tcp://samba.smb.test:88
    entrypoint: tail -f /dev/null
    networks:
      - default
      - default2
    volumes:
      - .:/smb

networks:
  default:
    driver: bridge
  default2:
    driver: bridge
