[package]
name = "smb-tests"
description = "Test utilities for smb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hex = "0.4"
pastey = { workspace = true }
